# Generated by Django 4.2.5 on 2023-09-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aboutme',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
