# Generated by Django 4.2.5 on 2023-09-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_aboutme_remove_user_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dateregister',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
