# Generated by Django 4.2.5 on 2023-10-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_active_remove_user_dateregister_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='food', upload_to=''),
        ),
    ]
